# Generated by Django 5.1.6 on 2025-03-02 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carreras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='duracion',
            field=models.FloatField(blank=True, default=3.5, max_length=4),
        ),
    ]
