# Generated by Django 5.1.6 on 2025-03-02 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_alter_alumno_apellidos_alter_alumno_telefono'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='is_active',
            field=models.BooleanField(default=True, null=True, verbose_name='Activo'),
        ),
    ]
