# Generated by Django 5.1.6 on 2025-03-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0004_alter_alumno_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='semestre',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
