# Generated by Django 5.1.6 on 2025-03-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0005_alter_alumno_semestre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
