# Generated by Django 5.1.6 on 2025-03-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0006_alter_alumno_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='matricula',
            field=models.CharField(blank=True, max_length=15, unique=True),
        ),
    ]
