# Generated by Django 5.1.6 on 2025-03-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0008_alter_alumno_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Activo'),
        ),
    ]
