# Generated by Django 5.1.6 on 2025-03-04 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0009_alter_alumno_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='fecha_ingreso',
            field=models.DateField(),
        ),
    ]
