# Generated by Django 5.1.6 on 2025-03-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0010_alter_alumno_fecha_ingreso'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='dia',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
