# Generated by Django 5.1.6 on 2025-03-17 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0011_alumno_dia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='dia',
        ),
        migrations.CreateModel(
            name='AlumnoDia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miercoles', 'Miercoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sabado', 'Sabado')], max_length=100)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='estudiantes.alumno')),
            ],
            options={
                'verbose_name': 'Alumno Dia',
                'verbose_name_plural': 'Alumnos Dias',
            },
        ),
        migrations.CreateModel(
            name='AlumnoDocumentosEntregados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acta_nacimiento', models.BooleanField(default=False)),
                ('certificado_bachillerato', models.BooleanField(default=False)),
                ('curp', models.BooleanField(default=False)),
                ('certificado_medico', models.BooleanField(default=False)),
                ('folder', models.BooleanField(default=False)),
                ('alumno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='documentos_entregados', to='estudiantes.alumno')),
            ],
        ),
    ]
