# Generated by Django 5.1.6 on 2025-03-17 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0012_remove_alumno_dia_alumnodia_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='apellidos',
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellido_materno',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alumno',
            name='apellido_paterno',
            field=models.CharField(default='', max_length=255),
        ),
    ]
