# Generated by Django 5.1.6 on 2025-03-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0013_remove_alumno_apellidos_alumno_apellido_materno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='correo',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
