# Generated by Django 5.1.6 on 2025-03-17 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0014_alumno_observaciones_alter_alumno_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnodocumentosentregados',
            name='alumno',
        ),
        migrations.AddField(
            model_name='alumno',
            name='documentos_entregados',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='estudiantes.alumnodocumentosentregados'),
        ),
    ]
