# Generated by Django 5.1.6 on 2025-03-17 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domicilios', '0001_initial'),
        ('estudiantes', '0016_remove_alumno_documentos_entregados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='direccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alumnos_direccion', to='domicilios.direccion'),
        ),
    ]
