# Generated by Django 5.1.6 on 2025-03-02 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_usuario_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, verbose_name='Activo'),
        ),
    ]
