# Generated by Django 5.1.6 on 2025-03-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_alter_pago_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='tipo',
            field=models.CharField(choices=[('E', 'Efectivo'), ('T', 'Transferencia')], default='E', max_length=1),
        ),
    ]
